name: Build and Upload Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      ${{ matrix.os }}

    strategy:
      matrix:
        os: ["ubuntu:22.04", "ubuntu:24.04", "debian:stable", "debian:oldstable"]
        arch: ["amd64", "arm64", "armhf"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          echo "VERGEN_GIT_SEMVER=0.1.0" >> $GITHUB_ENV
          echo "VERGEN_GIT_SHA_SHORT=abcdef" >> $GITHUB_ENV
          echo "VERGEN_BUILD_TIMESTAMP=2024-07-15T00:00:00Z" >> $GITHUB_ENV
          echo "VERGEN_RUSTC_SEMVER=1.79.0" >> $GITHUB_ENV
          echo "VERGEN_CARGO_TARGET_TRIPLE=x86_64-unknown-linux-gnu" >> $GITHUB_ENV
          echo "VERGEN_CARGO_PROFILE=release" >> $GITHUB_ENV

      - name: Install curl, wget, and node
        run: |
          apt-get update
          apt-get install -y curl wget
          apt-get install -y nodejs
          apt-get install -y build-essential
          apt-get install -y docker.io
          apt-get install -y gcc-aarch64-linux-gnu
          apt-get install -y gcc-arm-linux-gnueabihf


      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Install target
        run: rustup target add x86_64-unknown-linux-gnu
        if: matrix.arch == 'amd64'
      - run: rustup target add aarch64-unknown-linux-gnu
        if: matrix.arch == 'arm64'
      - run: rustup target add armv7-unknown-linux-gnueabihf
        if: matrix.arch == 'armhf'

      - name: Build Debian package
        run: cargo deb --target x86_64-unknown-linux-gnu
        if: matrix.arch == 'amd64'
      - run: cargo deb --target aarch64-unknown-linux-gnu
        if: matrix.arch == 'arm64'
      - run: cargo deb --target armv7-unknown-linux-gnueabihf
        if: matrix.arch == 'armhf'

      - name: Upload Debian package
        uses: actions/upload-artifact@v2
        with:
          name: debian-package-${{ matrix.arch }}
          path: |
            target/x86_64-unknown-linux-gnu/debian/*.deb
            target/aarch64-unknown-linux-gnu/debian/*.deb
            target/armv7-unknown-linux-gnueabihf/debian/*.deb
